version: "3"

services:
  app:
    image: packet-tracer-docker
    build:
      context: .
      args:
        DOCKER_USER: ${DOCKER_USER}
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/home/${DOCKER_USER}/.Xauthority
      - "${PWD}/Cisco_Packet_Tracer/:/home/${DOCKER_USER}/.local/share/Cisco Packet Tracer"
      - ${PWD}/pt/:/home/${DOCKER_USER}/pt/
    network_mode: host

